# Default values for arl-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

worker:
  replicaCount: 3

arldatadir: ./data

image:
  repository: arl
  tag: ubuntu18.04
  pullPolicy: IfNotPresent
  pullSecret: gitlab-registry

jupyter:
  password: changeme

nfs:
  server: 192.168.0.168

notebook:
  service:
    jupyter:
      port: 8888

daskscheduler:
  service:
    type: ClusterIP
    scheduler:
      port: 8786
    bokeh:
      port: 8787

resources:
  limits:
   cpu: 500m     # 500m = 0.5 CPU
   memory: 512Mi # 512Mi = 0.5 GB mem

# Configure Ingress resource that allow you to access the Tango REST API
ingress:
  enabled: true
  hostname: arl.minikube.local

  # Ingress annotations
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/x-forwarded-prefix: true
    nginx.ingress.kubernetes.io/ssl-redirect: false

  # Ingress TLS configuration
  #
  tls:
    enabled: true
    secretname: "tls-secret-arl-{{ .Release.Name }}"
    hostname: "{{ .Values.ingress.hostname }}"


nodeSelector: {}

tolerations: []

affinity: {}
