image: "python:3.7"

before_script:
  - pip install -r requirements.txt

stages:
  - test

variables:
  MPLBACKEND: "agg"

test:
  stage: test
  script:
    - pip install -r requirements-test.txt
    - py.test tests -n 4 --verbose
      --cov=processing_library
      --cov=processing_components
      --cov=workflows
      --cov-report=html:coverage tests
  artifacts:
    paths:
      - coverage/

docs:
  stage: test
  script:
    - apt-cache update
    - apt-get install pandoc
    - pip install -r requirements-docs.txt
    - make -k -j -C docs html
  artifacts:
    paths:
      - docs/build/html/
