image: "python:3.7"

before_script:
  - echo 'Installing requirements'
  - pip install -r requirements.txt

stages:
  - build
  - test
  - deploy

variables:
  MPLBACKEND: "agg"

build:
  stage: build
  script:
    - python setup.py install

test:
  stage: test
  script:
    - pip install pytest pytest-xdist pytest-cov
    - py.test tests -n 4 --verbose
      --cov=processing_library
      --cov=processing_components
      --cov=workflows
      --cov-report=html:coverage tests

deploy:
  stage: deploy
  script:
    - make -k -j -C docs html
