image: "python:3.7"

stages:
  - test

variables:
  MPLBACKEND: "agg"

test:
  stage: test
  before_script:
    - pip install -r requirements.txt -r requirements-test.txt
  script:
    - py.test tests -n 4 --verbose
      --cov=processing_library
      --cov=processing_components
      --cov=workflows
      --cov-report=html:coverage tests
  artifacts:
    paths:
      - coverage/
    expire_in: 1 week

docs:
  stage: test
  before_script:
    - apt-get update
    - apt-get -y install pandoc
    - pip install -r requirements.txt -r requirements-docs.txt
  script:
    - make -k -j -C docs html
  after_script:
    - mv docs/build/html html
  artifacts:
    paths:
      - html/
    expire_in: 1 week
