
NBs = imaging.ipynb imaging-wterm.ipynb imaging-fits.ipynb imaging-mfs.ipynb rcal.ipynb skymodel_cal.ipynb \
    imaging-spectral.ipynb simple-dask.ipynb plot-imaging-results.ipynb
include ../jupyter.mk
