""" Visibility iterators for iterating through a BlockVisibility or Visibility.

"""
from arl.processing_components.visibility.gather_scatter import visibility_scatter
from arl.processing_components.visibility.gather_scatter import visibility_gather
from arl.processing_components.visibility.gather_scatter import visibility_scatter_w
from arl.processing_components.visibility.gather_scatter import visibility_scatter_time
from arl.processing_components.visibility.gather_scatter import visibility_gather_w
from arl.processing_components.visibility.gather_scatter import visibility_gather_time
from arl.processing_components.visibility.gather_scatter import visibility_scatter_channel
from arl.processing_components.visibility.gather_scatter import visibility_gather_channel