"""
Functions that aid testing in various ways. 
"""

from arl.processing_components.simulation import create_test_image
from arl.processing_components.simulation import create_test_image_from_s3
from arl.processing_components.simulation import create_low_test_image_from_gleam
from arl.processing_components.simulation import create_low_test_skymodel_from_gleam
from arl.processing_components.simulation import create_low_test_skycomponents_from_gleam
from arl.processing_components.simulation import create_test_skycomponents_from_s3
from arl.processing_components.simulation import replicate_image
from arl.processing_components.simulation import create_blockvisibility_iterator
from arl.processing_components.simulation import simulate_gaintable
from arl.processing_components.simulation import simulate_pointingtable
from arl.processing_components.simulation import simulate_pointingtable_from_timeseries
from arl.processing_components.simulation import ingest_unittest_visibility
from arl.processing_components.simulation import create_unittest_components
from arl.processing_components.simulation import create_unittest_model
from arl.processing_components.simulation import insert_unittest_errors