"""
Functions that aid testing in various ways. 
"""

from processing_components.simulation import create_configuration_from_file, create_LOFAR_configuration, create_named_configuration
from processing_components.simulation import create_test_image
from processing_components.simulation import create_test_image_from_s3
from processing_components.simulation import create_low_test_image_from_gleam
from processing_components.simulation import create_low_test_skymodel_from_gleam
from processing_components.simulation import create_low_test_skycomponents_from_gleam
from processing_components.simulation import replicate_image
from processing_components.simulation import create_blockvisibility_iterator
from processing_components.simulation import simulate_gaintable
from processing_components.simulation import ingest_unittest_visibility
from processing_components.simulation import create_unittest_components
from processing_components.simulation import create_unittest_model
from processing_components.simulation import insert_unittest_errors