/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: arl.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "arl.pb-c.h"
void   uvw__init
                     (UVW         *message)
{
  static UVW init_value = UVW__INIT;
  *message = init_value;
}
size_t uvw__get_packed_size
                     (const UVW *message)
{
  assert(message->base.descriptor == &uvw__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t uvw__pack
                     (const UVW *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &uvw__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t uvw__pack_to_buffer
                     (const UVW *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &uvw__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UVW *
       uvw__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UVW *)
     protobuf_c_message_unpack (&uvw__descriptor,
                                allocator, len, data);
}
void   uvw__free_unpacked
                     (UVW *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &uvw__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vis__init
                     (VIS         *message)
{
  static VIS init_value = VIS__INIT;
  *message = init_value;
}
size_t vis__get_packed_size
                     (const VIS *message)
{
  assert(message->base.descriptor == &vis__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vis__pack
                     (const VIS *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vis__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vis__pack_to_buffer
                     (const VIS *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vis__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VIS *
       vis__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VIS *)
     protobuf_c_message_unpack (&vis__descriptor,
                                allocator, len, data);
}
void   vis__free_unpacked
                     (VIS *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &vis__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   data__init
                     (Data         *message)
{
  static Data init_value = DATA__INIT;
  *message = init_value;
}
size_t data__get_packed_size
                     (const Data *message)
{
  assert(message->base.descriptor == &data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t data__pack
                     (const Data *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t data__pack_to_buffer
                     (const Data *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Data *
       data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Data *)
     protobuf_c_message_unpack (&data__descriptor,
                                allocator, len, data);
}
void   data__free_unpacked
                     (Data *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   phasecentre__init
                     (Phasecentre         *message)
{
  static Phasecentre init_value = PHASECENTRE__INIT;
  *message = init_value;
}
size_t phasecentre__get_packed_size
                     (const Phasecentre *message)
{
  assert(message->base.descriptor == &phasecentre__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t phasecentre__pack
                     (const Phasecentre *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &phasecentre__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t phasecentre__pack_to_buffer
                     (const Phasecentre *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &phasecentre__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Phasecentre *
       phasecentre__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Phasecentre *)
     protobuf_c_message_unpack (&phasecentre__descriptor,
                                allocator, len, data);
}
void   phasecentre__free_unpacked
                     (Phasecentre *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &phasecentre__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   arlvis_pb__init
                     (ARLVisPB         *message)
{
  static ARLVisPB init_value = ARLVIS_PB__INIT;
  *message = init_value;
}
size_t arlvis_pb__get_packed_size
                     (const ARLVisPB *message)
{
  assert(message->base.descriptor == &arlvis_pb__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t arlvis_pb__pack
                     (const ARLVisPB *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &arlvis_pb__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t arlvis_pb__pack_to_buffer
                     (const ARLVisPB *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &arlvis_pb__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ARLVisPB *
       arlvis_pb__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ARLVisPB *)
     protobuf_c_message_unpack (&arlvis_pb__descriptor,
                                allocator, len, data);
}
void   arlvis_pb__free_unpacked
                     (ARLVisPB *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &arlvis_pb__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor uvw__field_descriptors[3] =
{
  {
    "u",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(UVW, u),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(UVW, v),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(UVW, w),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned uvw__field_indices_by_name[] = {
  0,   /* field[0] = u */
  1,   /* field[1] = v */
  2,   /* field[2] = w */
};
static const ProtobufCIntRange uvw__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor uvw__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UVW",
  "UVW",
  "UVW",
  "",
  sizeof(UVW),
  3,
  uvw__field_descriptors,
  uvw__field_indices_by_name,
  1,  uvw__number_ranges,
  (ProtobufCMessageInit) uvw__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vis__field_descriptors[2] =
{
  {
    "real",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(VIS, real),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "imag",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(VIS, imag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vis__field_indices_by_name[] = {
  1,   /* field[1] = imag */
  0,   /* field[0] = real */
};
static const ProtobufCIntRange vis__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor vis__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VIS",
  "VIS",
  "VIS",
  "",
  sizeof(VIS),
  2,
  vis__field_descriptors,
  vis__field_indices_by_name,
  1,  vis__number_ranges,
  (ProtobufCMessageInit) vis__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor data__field_descriptors[11] =
{
  {
    "index",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Data, n_index),
    offsetof(Data, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uvw",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Data, n_uvw),
    offsetof(Data, uvw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Data, n_time),
    offsetof(Data, time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "frequency",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Data, n_frequency),
    offsetof(Data, frequency),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channel_bandwidth",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Data, n_channel_bandwidth),
    offsetof(Data, channel_bandwidth),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "integration_time",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Data, n_integration_time),
    offsetof(Data, integration_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "antenna1",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Data, n_antenna1),
    offsetof(Data, antenna1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "antenna2",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Data, n_antenna2),
    offsetof(Data, antenna2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vis",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Data, n_vis),
    offsetof(Data, vis),
    &vis__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "weight",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Data, n_weight),
    offsetof(Data, weight),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "imaging_weight",
    11,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Data, n_imaging_weight),
    offsetof(Data, imaging_weight),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned data__field_indices_by_name[] = {
  6,   /* field[6] = antenna1 */
  7,   /* field[7] = antenna2 */
  4,   /* field[4] = channel_bandwidth */
  3,   /* field[3] = frequency */
  10,   /* field[10] = imaging_weight */
  0,   /* field[0] = index */
  5,   /* field[5] = integration_time */
  2,   /* field[2] = time */
  1,   /* field[1] = uvw */
  8,   /* field[8] = vis */
  9,   /* field[9] = weight */
};
static const ProtobufCIntRange data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Data",
  "Data",
  "Data",
  "",
  sizeof(Data),
  11,
  data__field_descriptors,
  data__field_indices_by_name,
  1,  data__number_ranges,
  (ProtobufCMessageInit) data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor phasecentre__field_descriptors[2] =
{
  {
    "ra",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Phasecentre, ra),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dec",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Phasecentre, dec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned phasecentre__field_indices_by_name[] = {
  1,   /* field[1] = dec */
  0,   /* field[0] = ra */
};
static const ProtobufCIntRange phasecentre__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor phasecentre__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Phasecentre",
  "Phasecentre",
  "Phasecentre",
  "",
  sizeof(Phasecentre),
  2,
  phasecentre__field_descriptors,
  phasecentre__field_indices_by_name,
  1,  phasecentre__number_ranges,
  (ProtobufCMessageInit) phasecentre__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor arlvis_pb__field_descriptors[4] =
{
  {
    "nvis",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ARLVisPB, nvis),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "npol",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ARLVisPB, npol),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ARLVisPB, data),
    &data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phasecentre",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ARLVisPB, phasecentre),
    &phasecentre__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned arlvis_pb__field_indices_by_name[] = {
  2,   /* field[2] = data */
  1,   /* field[1] = npol */
  0,   /* field[0] = nvis */
  3,   /* field[3] = phasecentre */
};
static const ProtobufCIntRange arlvis_pb__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor arlvis_pb__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ARLVisPB",
  "ARLVisPB",
  "ARLVisPB",
  "",
  sizeof(ARLVisPB),
  4,
  arlvis_pb__field_descriptors,
  arlvis_pb__field_indices_by_name,
  1,  arlvis_pb__number_ranges,
  (ProtobufCMessageInit) arlvis_pb__init,
  NULL,NULL,NULL    /* reserved[123] */
};
