# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arl.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='arl.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\tarl.proto\"&\n\x03UVW\x12\t\n\x01u\x18\x01 \x02(\x01\x12\t\n\x01v\x18\x02 \x02(\x01\x12\t\n\x01w\x18\x03 \x02(\x01\"!\n\x03VIS\x12\x0c\n\x04real\x18\x01 \x02(\x01\x12\x0c\n\x04imag\x18\x02 \x02(\x01\"\xd7\x01\n\x04\x44\x61ta\x12\r\n\x05index\x18\x01 \x03(\x05\x12\x0b\n\x03uvw\x18\x02 \x03(\x01\x12\x0c\n\x04time\x18\x03 \x03(\x01\x12\x11\n\tfrequency\x18\x04 \x03(\x01\x12\x19\n\x11\x63hannel_bandwidth\x18\x05 \x03(\x01\x12\x18\n\x10integration_time\x18\x06 \x03(\x01\x12\x10\n\x08\x61ntenna1\x18\x07 \x03(\x05\x12\x10\n\x08\x61ntenna2\x18\x08 \x03(\x05\x12\x11\n\x03vis\x18\t \x03(\x0b\x32\x04.VIS\x12\x0e\n\x06weight\x18\n \x03(\x01\x12\x16\n\x0eimaging_weight\x18\x0b \x03(\x01\"&\n\x0bPhasecentre\x12\n\n\x02ra\x18\x01 \x02(\t\x12\x0b\n\x03\x64\x65\x63\x18\x02 \x02(\t\"^\n\x08\x41RLVisPB\x12\x0c\n\x04nvis\x18\x01 \x02(\x05\x12\x0c\n\x04npol\x18\x02 \x02(\x05\x12\x13\n\x04\x64\x61ta\x18\x03 \x02(\x0b\x32\x05.Data\x12!\n\x0bphasecentre\x18\x04 \x02(\x0b\x32\x0c.Phasecentre')
)




_UVW = _descriptor.Descriptor(
  name='UVW',
  full_name='UVW',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='u', full_name='UVW.u', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v', full_name='UVW.v', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w', full_name='UVW.w', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=51,
)


_VIS = _descriptor.Descriptor(
  name='VIS',
  full_name='VIS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='real', full_name='VIS.real', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imag', full_name='VIS.imag', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=86,
)


_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='Data.index', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uvw', full_name='Data.uvw', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='Data.time', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frequency', full_name='Data.frequency', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel_bandwidth', full_name='Data.channel_bandwidth', index=4,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='integration_time', full_name='Data.integration_time', index=5,
      number=6, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='antenna1', full_name='Data.antenna1', index=6,
      number=7, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='antenna2', full_name='Data.antenna2', index=7,
      number=8, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vis', full_name='Data.vis', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weight', full_name='Data.weight', index=9,
      number=10, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imaging_weight', full_name='Data.imaging_weight', index=10,
      number=11, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=304,
)


_PHASECENTRE = _descriptor.Descriptor(
  name='Phasecentre',
  full_name='Phasecentre',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ra', full_name='Phasecentre.ra', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dec', full_name='Phasecentre.dec', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=344,
)


_ARLVISPB = _descriptor.Descriptor(
  name='ARLVisPB',
  full_name='ARLVisPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nvis', full_name='ARLVisPB.nvis', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='npol', full_name='ARLVisPB.npol', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='ARLVisPB.data', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phasecentre', full_name='ARLVisPB.phasecentre', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=346,
  serialized_end=440,
)

_DATA.fields_by_name['vis'].message_type = _VIS
_ARLVISPB.fields_by_name['data'].message_type = _DATA
_ARLVISPB.fields_by_name['phasecentre'].message_type = _PHASECENTRE
DESCRIPTOR.message_types_by_name['UVW'] = _UVW
DESCRIPTOR.message_types_by_name['VIS'] = _VIS
DESCRIPTOR.message_types_by_name['Data'] = _DATA
DESCRIPTOR.message_types_by_name['Phasecentre'] = _PHASECENTRE
DESCRIPTOR.message_types_by_name['ARLVisPB'] = _ARLVISPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UVW = _reflection.GeneratedProtocolMessageType('UVW', (_message.Message,), dict(
  DESCRIPTOR = _UVW,
  __module__ = 'arl_pb2'
  # @@protoc_insertion_point(class_scope:UVW)
  ))
_sym_db.RegisterMessage(UVW)

VIS = _reflection.GeneratedProtocolMessageType('VIS', (_message.Message,), dict(
  DESCRIPTOR = _VIS,
  __module__ = 'arl_pb2'
  # @@protoc_insertion_point(class_scope:VIS)
  ))
_sym_db.RegisterMessage(VIS)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(
  DESCRIPTOR = _DATA,
  __module__ = 'arl_pb2'
  # @@protoc_insertion_point(class_scope:Data)
  ))
_sym_db.RegisterMessage(Data)

Phasecentre = _reflection.GeneratedProtocolMessageType('Phasecentre', (_message.Message,), dict(
  DESCRIPTOR = _PHASECENTRE,
  __module__ = 'arl_pb2'
  # @@protoc_insertion_point(class_scope:Phasecentre)
  ))
_sym_db.RegisterMessage(Phasecentre)

ARLVisPB = _reflection.GeneratedProtocolMessageType('ARLVisPB', (_message.Message,), dict(
  DESCRIPTOR = _ARLVISPB,
  __module__ = 'arl_pb2'
  # @@protoc_insertion_point(class_scope:ARLVisPB)
  ))
_sym_db.RegisterMessage(ARLVisPB)


# @@protoc_insertion_point(module_scope)
