"""Function to manage sky components.

"""
from arl.processing_components.skycomponent.operations import create_skycomponent
from arl.processing_components.skycomponent.operations import find_nearest_skycomponent_index
from arl.processing_components.skycomponent.operations import find_nearest_skycomponent
from arl.processing_components.skycomponent.operations import find_separation_skycomponents
from arl.processing_components.skycomponent.operations import find_skycomponent_matches_atomic
from arl.processing_components.skycomponent.operations import find_skycomponent_matches
from arl.processing_components.skycomponent.operations import find_skycomponents
from arl.processing_components.skycomponent.operations import apply_beam_to_skycomponent
from arl.processing_components.skycomponent.operations import insert_skycomponent
from arl.processing_components.skycomponent.operations import filter_skycomponents_by_flux
from arl.processing_components.skycomponent.operations import select_neighbouring_components
from arl.processing_components.skycomponent.operations import image_voronoi_iter
from arl.processing_components.skycomponent.operations import voronoi_decomposition
from arl.processing_components.skycomponent.operations import partition_skycomponent_neighbours
from arl.processing_components.skycomponent.operations import remove_neighbouring_components
