"""Manages the calibration context.
"""
from processing_components.calibration.calibration_control import create_calibration_controls
from processing_components.calibration.calibration_control import calibrate_function
from processing_components.calibration.calibration_control import apply_calibration_function
from processing_components.calibration.calibration_control import solve_calibrate_function