"""Function to manage sky components.

"""
from processing_components.skycomponent.operations import create_skycomponent
from processing_components.skycomponent.operations import find_nearest_skycomponent_index
from processing_components.skycomponent.operations import find_nearest_skycomponent
from processing_components.skycomponent.operations import find_separation_skycomponents
from processing_components.skycomponent.operations import find_skycomponent_matches_atomic
from processing_components.skycomponent.operations import find_skycomponent_matches
from processing_components.skycomponent.operations import select_components_by_separation
from processing_components.skycomponent.operations import select_components_by_flux
from processing_components.skycomponent.operations import find_skycomponents
from processing_components.skycomponent.operations import apply_beam_to_skycomponent
from processing_components.skycomponent.operations import insert_skycomponent
from processing_components.skycomponent.operations import filter_skycomponents_by_flux