
NBs = simple-dask_arlexecute.ipynb imaging_serial.ipynb imaging-fits_arlexecute.ipynb \
imaging-wterm_arlexecute.ipynb imaging-pipelines_arlexecute.ipynb bandpass-calibration_arlexecute.ipynb
include ../jupyter.mk
