
NBs = simple-dask_arlexecute.ipynb imaging-pipelines_arlexecute.ipynb imaging_serial.ipynb imaging-fits_serial.ipynb \
imaging-wterm_serial.ipynb rcal_serial.ipynb # modelpartition_arlexecute.ipynb
include ../jupyter.mk
